version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: ./operations/docker/postgresql/Dockerfile
    ports:
      - "5452:5432"
    volumes:
      - apiko_data:/var/lib/postgresql/data
    networks:
      - apiko_network

  api:
    build:
      context: .
      dockerfile: ./operations/docker/api/Dockerfile
      args:
        - NODE_ENV=development
    command: npm run dev
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/home/nodejs/app
    networks:
      - apiko_network

volumes:
  apiko_data:

networks:
  apiko_network:
